### ISSUE TITLE
IssueList APIError: 'cover_date' field may not be null.

### ISSUE THREAD

**Issue by jakem742** [Buried-In-Code/Simyan#100]
I have encountered the same issue as #86 with the 'cover_date' field in Issue_List. Not exactly the same, but close enough? Unfortunately I was ~1hr into running a script and didn't have logging enabled, so can't point you to the Volume that caused this until I rerun with error handling fixed. 

Would it perhaps make sense to have this exception handled in a way that doesn't kill the script that I'm running? Maybe a default value for each field when this occurs?

 The line in my code: 

`results = session.issue_list(params={"filter": "volume:%s" % (comicID)})`
    
The traceback:

```
  File "/Users/user/Downloads/CBL-ReadingLists-main/tools/simyan/session.py", line 252, in issue_list
    return IssueList(results)
  File "/Users/user/Downloads/CBL-ReadingLists-main/tools/simyan/issue_list.py", line 103, in __init__
    raise APIError(error)
simyan.exceptions.APIError: {'cover_date': ['Field may not be null.']}
```

**Comment by jakem742** [comment]
I've re-run the test and found the comicID in question: 3088. All issues have "No Date" as the date value.

https://comicvine.gamespot.com/marvel-super-heroes/4050-3088/

**Comment by Buried-In-Code** [comment]
Thanks for point that out, should be easy enough to fix.
The Comicvine API is pretty badly documented for its response types, so its not the first issue like this.

> Would it perhaps make sense to have this exception handled in a way that doesn't kill the script that I'm running? Maybe a default value for each field when this occurs?

You could try wrapping it in a try/except
```python
try:
    results = session.issue_list(params={"filter": "volume:%s" % (comicID)})
except APIError as err:
    print(f"Error while loading {comicID}: {err}")
```
