### ISSUE TITLE
'/search' endpoint

### ISSUE THREAD

**Issue by themadman0980** [Buried-In-Code/Simyan#109]
I can't see this functionality anywhere presently? I need to run a query in the following format:

https://comicvine.gamespot.com/api/search/?api_key=5555555555&format=json&resources=volume&limit=100&query=logans+run

I am finding that using volume_list with a name filter is failing to return some matches that aren't an exact fit. My current query using Simyan is:

comicvine.volume_list(params={"filter": "name:%s" % (seriesName)})

An example of my problem is the series "Logan's Run". If I search for "Logans Run" (no apostrophe) the volume_list with a name filter returns 0 results. The same search using the URL at the top returns the correct series in the results.

I am assuming that the filter by name only returns exact string matches, which is the cause of my problems?

**Comment by Buried-In-Code** [comment]
The `/search` endpoint doesn't follow the same pattern as the other endpoints so I hadn't implemented it yet, but I'll take another look and see if I can get something put together.

**Comment by themadman0980** [comment]
Thanks. :) 

If it's unlikely to happen for a while I'll just make my own custom calls, but I'd like to keep using Simyan for everything if possible.

**Comment by Buried-In-Code** [comment]
Ive managed to hopefully solve it, just some cleanup and docs left to do, hopefully should have a solution out soon
