### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by bpepple** [Buried-In-Code/Simyan#38]
I've started to add documentation support (Readthedocs), which can be tracked at this branch, and should have most of it ready for review by the end of the week:

https://github.com/bpepple/Simyan/tree/documentation

**Comment by Buried-In-Code** [comment]
That's awesome, thank you. I've thought about setting one up, however never have previously and didn't want to deal with certs, hosting, etc... I assume **ReadTheDocs** manages all that some how?
